title: Hello, world! I'm Vipul Jain
description: > # this means to ignore newlines until "baseurl:"
  I am a software engineer, currently working in Amazon, Bangalore, India.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thevipuljain.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/jainvipul1994"

# Author Settings
author: Vipul Jain # add your name
author-img: vipul-jain.jpeg # add your photo
about-author: I am a software engineer. Always hungry to keep learning. # add description
social-twitter: jainvipul1994
# social-facebook: # add your Facebook handle
# social-github: vipul1994 # add your Github handle
# social-linkedin: # add your Linkedin handle
# social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
